apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-tjffzvlo
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-tjffzvlo:b1861cbfc40f65a3e28fd21bea43ae327a474cb9@sha256:7544660324c1ace68b54d425544b9a1ac6c24dde459aaf48cbda4fcc3b2cff79
        name: container-image  
